export enum CATEGORY {
	AUTO = 'Auto',
	DINING = 'Dining',
	FINANCES = 'Finances',
	GIFT = 'Gift',
	GOINGOUT = 'Going out',
	GROCERIES = 'Groceries',
	GYM = 'Gym',
	LEISURE = 'Leisure',
	HOUSEHOLD = 'Household',
	MEDICAL = 'Medical',
	SERVICES = 'Services',
	SHOPPING = 'Shopping',
	SUBS = 'Subscription',
	TAXES = 'Taxes',
	TECH = 'Tech',
	TRANSPORT = 'Transportation',
	TRAVEL = 'Travel',
	UTILITIES = 'Utilities',
	OTHER = 'Other'
}
